version: "2"
services:
  fargate-php-test-dev:
    image: 442639372443.dkr.ecr.us-east-1.amazonaws.com/fargate-php-test:0.1.0-5
    ports:
    - 80:80
    environment:
      HEALTHCHECK: /healthcheck
      PORT: "80"
    env_file:
    - hidden.env
